src/Entity/Campus.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CampusRepository")
 */
class Campus
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $CampusId;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $nomCampus;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Sortie", mappedBy="campus"))
     */
    private $sorties;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Utilisateur", mappedBy="campus"))
     */
    private $utilisateurs;

    /**
     * @return mixed
     */
    public function getCampusId()
    {
        return $this->CampusId;
    }

    /**
     * @return mixed
     */
    public function getNomCampus()
    {
        return $this->nomCampus;
    }

    /**
     * @param mixed $nomCampus
     */
    public function setNomCampus($nomCampus): void
    {
        $this->nomCampus = $nomCampus;
    }

    /**
     * @return mixed
     */
    public function getSorties()
    {
        return $this->sorties;
    }

    /**
     * @param mixed $sorties
     */
    public function setSorties($sorties): void
    {
        $this->sorties = $sorties;
    }

}

src/Form/CampusType.php
<?php

namespace App\Form;

use App\Entity\Campus;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class CampusType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nomCampus', TextType::class, ['label' => ' ' , 'required'=>true])
            ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Campus::class
        ]);
    }
}

src/Controller/CampusController.php
<?php


namespace App\Controller;


use App\Entity\Campus;
use App\Form\CampusType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/campus")
 */
class CampusController extends AbstractController
{

    /**
     * @Route("/",name="campus")
     *
     */
    public function afficherCampus(EntityManagerInterface $em,
                                   Request $request){

        $campusRepo = $this->getDoctrine()->getRepository(Campus::class);
        $campus = $campusRepo->findAll();

        $campus2= new Campus();
        $formCampus = $this->createForm(CampusType::class, $campus2);
        $formCampus->handleRequest($request);
        if(isset($_POST['submit']) && $formCampus->isSubmitted() && $formCampus->isValid())
        {
            $em->persist($campus2);
            $em->flush();

            return $this->redirectToRoute('campus',["campus"=>$campus]);
        }



        return $this->render("campus/campus.html.twig",["campus"=>$campus, "formCampus"=>$formCampus->createView()]);
    }
    /**
     * @Route("/supprimer/{id}", name="campus_supprimer", requirements={"id": "\d+" });
     */
    public function supprimer($id, EntityManagerInterface $em,
                              Request $request){

        $campusRepo = $this->getDoctrine()->getRepository(Campus::class);
        $campusSup =$campusRepo->find($id);

        $em->remove($campusSup);
        $em->flush();

        $campusRepo = $this->getDoctrine()->getRepository(Campus::class);
        $campus = $campusRepo->findAll();

        $campus2= new Campus();
        $formCampus = $this->createForm(CampusType::class, $campus2);
        $formCampus->handleRequest($request);

        return $this->render('campus/campus.html.twig', [
            "campus"=>$campus, "formCampus"=>$formCampus->createView()
        ]);
    }
    /**
     * @Route("/modifier/{id}", name="campus_modifier", requirements={"id": "\d+" });
     */
    public function modifier($id, EntityManagerInterface $em,
                              Request $request)
    {
        $campusRepo = $this->getDoctrine()->getRepository(Campus::class);
        $campus = $campusRepo->findAll();

        $campus2= $campusRepo->find($id);
        $formCampus = $this->createForm(CampusType::class, $campus2);
        $formCampus->handleRequest($request);
        if(isset($_POST['submit']) && $formCampus->isSubmitted() && $formCampus->isValid())
        {
            $em->persist($campus2);
            $em->flush();

            return $this->redirectToRoute('campus',["campus"=>$campus]);
        }
        return $this->render("campus/modifier.html.twig",["campus"=>$campus, "formCampus"=>$formCampus->createView(), "id"=>$id]);
    }

}

templates/campus/campus.html.twig
{% extends 'layout.html.twig' %}

{% block main %}
    <table>
        <tr>
            <th>Campus</th>
            <th>Actions</th>
        </tr>
        {% for camp in campus %}
            <tr>
                <td>{{ camp.nomCampus }}</td>
                <td><a href="{{ path('campus_modifier', {'id': camp.campusId}) }}">Modifier</a>
                    <a href="{{ path('campus_supprimer', {'id': camp.campusId}) }}">Supprimer</a></td>
            </tr>
        {% endfor %}
        {{ form_start(formCampus) }}
        <td>{{ form_widget(formCampus) }}</td>
        <td><button type="submit" name="submit" id="submit">Ajouter</button></td>
        {{ form_end(formCampus) }}
    </table>

{% endblock %}

{% block title %}Campus{% endblock %}

templates/campus/modifier.html.twig
{% extends 'layout.html.twig' %}

{% block main %}
    <table>
        <tr>
            <th>Campus</th>
            <th>Actions</th>
        </tr>
        {% for camp in campus %}
            <tr>
             {% if(camp.campusId!=id) %}
                <td>{{ camp.nomCampus }}</td>
                <td>Modifier Supprimer</td>
             {% elseif(camp.campusId==id) %}
                 {{ form_start(formCampus) }}
                 <td>{{ form_widget(formCampus) }}</td>
                 <td><button type="submit" name="submit" id="submit">Modifier</button></td>
                 {{ form_end(formCampus) }}
            {% endif %}
            </tr>
        {% endfor %}
    </table>

{% endblock %}

{% block title %}Campus{% endblock %}