src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;


/**
 * @UniqueEntity(fields={"email"})
 * @ORM\Table(name="utilisateur")
 * @ORM\Entity(repositoryClass="App\Repository\UtilisateurRepository")
 */
class Utilisateur implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $UserId;

    /**
     * @ORM\Column(type="string", length=50, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=100, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateCreation;

    /**
     * @ORM\Column(type="boolean")
     */
    private $administrateur;

    /**
     * @ORM\Column(type="boolean")
     */
    private $actif;


    /**
     * @var Utilisateur
     * @ORM\ManyToOne(targetEntity="App\Entity\Campus", inversedBy="utilisateurs")
     *  @ORM\JoinColumn(nullable=true, name="Campus", referencedColumnName="campus_id")
     */
    private $campus;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Sortie", mappedBy="organisateur"))
     * @ORM\JoinColumn(nullable=true)
     */
    private $sorties;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nomPhoto;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @var \DateTime
     */
    private $passwordRequestedAt;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $token;



    /**
     * @return mixed
     */
    public function getUserId()
    {
        return $this->UserId;
    }

    /**
     * @param mixed $UserId
     */
    public function setUserId($UserId): void
    {
        $this->UserId = $UserId;
    }

    /**
     * @return mixed
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * @param mixed $username
     */
    public function setUsername($username): void
    {
        $this->username = $username;
    }

    /**
     * @return mixed
     */
    public function getPrenom()
    {
        return $this->prenom;
    }

    /**
     * @param mixed $prenom
     */
    public function setPrenom($prenom): void
    {
        $this->prenom = $prenom;
    }

    /**
     * @return mixed
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * @param mixed $nom
     */
    public function setNom($nom): void
    {
        $this->nom = $nom;
    }

    /**
     * @return mixed
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param mixed $email
     */
    public function setEmail($email): void
    {
        $this->email = $email;
    }

    /**
     * @return mixed
     */
    public function getTelephone()
    {
        return $this->telephone;
    }

    /**
     * @param mixed $telephone
     */
    public function setTelephone($telephone): void
    {
        $this->telephone = $telephone;
    }

    /**
     * @return mixed
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * @param mixed $password
     */
    public function setPassword($password): void
    {
        $this->password = $password;
    }

    /**
     * @return mixed
     */
    public function getDateCreation()
    {
        return $this->dateCreation;
    }

    /**
     * @param mixed $dateCreation
     */
    public function setDateCreation($dateCreation): void
    {
        $this->dateCreation = $dateCreation;
    }

    /**
     * @return mixed
     */
    public function getAdministrateur()
    {
        return $this->administrateur;
    }

    /**
     * @param mixed $administrateur
     */
    public function setAdministrateur($administrateur): void
    {
        $this->administrateur = $administrateur;
    }

    /**
     * @return mixed
     */
    public function getCampus()
    {
        return $this->campus;
    }

    /**
     * @param mixed $campus
     */
    public function setCampus($campus): void
    {
        $this->campus = $campus;
    }

    /**
     * @return mixed
     */
    public function getNomPhoto()
    {
        return $this->nomPhoto;
    }

    /**
     * @param mixed $nomPhoto
     */
    public function setNomPhoto($nomPhoto): void
    {
        $this->nomPhoto = $nomPhoto;
    }

    /**
     * @return mixed
     */
    public function getActif()
    {
        return $this->actif;
    }

    /**
     * @param mixed $actif
     */
    public function setActif($actif): void
    {
        $this->actif = $actif;
    }

    /**
     * @return mixed
     */
    public function getSorties()
    {
        return $this->sorties;
    }

    /**
     * @param mixed $sorties
     */
    public function setSorties($sorties): void
    {
        $this->sorties = $sorties;
    }


    /**
     * @return mixed
     */
    public function getRoles()
    {
        if($this->administrateur==1)
        {
            return ["ROLE_ADMIN"];
        }
        else
        {
            return ["ROLE_USER"];
        }
    }

    /**
     * @param mixed $roles
     */
    public function setRoles($roles): void
    {
        $this->roles = $roles;
    }

    /**
     * @return \DateTime
     */
    public function getPasswordRequestedAt(): \DateTime
    {
        return $this->passwordRequestedAt;
    }

    /**
     * @param \DateTime $passwordRequestedAt
     */
    public function setPasswordRequestedAt(\DateTime $passwordRequestedAt): void
    {
        $this->passwordRequestedAt = $passwordRequestedAt;
    }

    /**
     * @return string
     */
    public function getToken(): string
    {
        return $this->token;
    }

    /**
     * @param string $token
     */
    public function setToken(string $token): void
    {
        $this->token = $token;
    }



    public function getSalt(){return null;}
    public function eraseCredentials()
    {}
}

src/Form/ProfilType.php
<?php

namespace App\Form;

use App\Entity\Utilisateur;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProfilType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username', TextType::class, ['label' => 'Pseudo'])
            ->add('prenom', TextType::class, ['label' => 'Prenom'])
            ->add('nom', TextType::class, ['label' => 'Nom'])
            ->add('telephone', TextType::class, ['label' => 'Téléphone'])
            ->add('email', EmailType::class, ['label' => 'Email'])
            ->add('password', RepeatedType::class, ['type'=>PasswordType::class,
                'invalid_message' => 'les mots de passes ne correspondent pas',
                'required'=>true,
                'first_options'=>array('label'=>'Mot de passe'),
                'second_options'=>array('label'=>'Répéter Mot de passe')])
            ->add('administrateur', ChoiceType::class, ['choices'=> ['Oui'=>true, 'Non'=>false]])
            ->add('actif', ChoiceType::class, ['choices'=> ['Oui'=>true, 'Non'=>false]])
            ->add('campus', EntityType::class, ['class' => 'App\Entity\Campus', 'choice_label'=> 'nomCampus','label' => 'Campus :', 'required'=>true])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class'=>Utilisateur::class
        ]);
    }
}

src/Controller/ProfilController.php
<?php


namespace App\Controller;


use App\Entity\Photo;
use App\Entity\Sortie;
use App\Entity\Utilisateur;
use App\Form\InscriptionType;

use App\Form\ProfilType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Core\User\UserInterface;


class ProfilController extends AbstractController
{
    /**
     * @Route("/inscription", name="inscription");
     */
    public function inscription(EntityManagerInterface $em,
                                Request $request,
                                UserPasswordEncoderInterface $encoder, UserInterface $user){

        $utilisateur = new Utilisateur();
        $utilisateur->setDateCreation(new \DateTime());

        $formInscription = $this->createForm(InscriptionType::class, $utilisateur);

        $formInscription->handleRequest($request);

        if( $formInscription->isSubmitted() && $formInscription->isValid()){

                $file = $utilisateur->getNomPhoto();
                $fileName = md5(uniqid()).'.'.$file->guessExtension();
                $file->move($this->getParameter('upload_directory'),$fileName);
                $utilisateur->setNomPhoto($fileName);

                $hashed = $encoder->encodePassword($utilisateur, $utilisateur->getPassword());
                $utilisateur->setPassword($hashed);

                $em->persist($utilisateur);
                $em->flush();

                return $this->redirectToRoute('accueil',['id'=>$utilisateur->getUserId(), "utilisateur"=>$user]);

            }


        return $this->render('profil/inscription.html.twig',
            ["formInscription"=>$formInscription->createView()]);
    }

    /**
     * @Route("/profil_modifier/{id}", name="profil_modifier", requirements={"id": "\d+" })
     */
    public function modifier($id, EntityManagerInterface $em,
                                Request $request, UserInterface $user,
                             UserPasswordEncoderInterface $encoder){


        $userRepo = $this->getDoctrine()->getRepository(Utilisateur::class);
        $utilisateur =$userRepo->find($id);

        $photo=null;
        $formInscription = $this->createForm(ProfilType::class, $utilisateur);
        $formInscription->handleRequest($request);

        if($formInscription->isSubmitted() && $formInscription->isValid()){

            $hashed = $encoder->encodePassword($utilisateur, $utilisateur->getPassword());
            $utilisateur->setPassword($hashed);

            $em->persist($utilisateur);
            $em->flush();

            $photoRepo = $this->getDoctrine()->getRepository(Photo::class);
            $photo = $photoRepo->find(2);


            if ($utilisateur->getUsername()==$user->getUsername()){
                return $this->redirectToRoute('accueil',[]);
            } else {
                return $this->redirectToRoute('profils',["photo"=>$photo]);
            }
        }

        return $this->render('profil/profil.html.twig', ["formInscription"=>$formInscription->createView(),"photo"=>$photo ,"utilisateur"=>$user]);
    }

    /**
     * @Route("/profils", name="profils")
     */
    public function listeUtilisateur(){

        $userRepo = $this->getDoctrine()->getRepository(Utilisateur::class);
        $utilisateurs =$userRepo->findAll();

        $photoRepo = $this->getDoctrine()->getRepository(Photo::class);
        $photo = $photoRepo->find(2);

        return $this->render('profil/profils.html.twig', [
          "utilisateurs"=>$utilisateurs, "photo"=>$photo]);
    }
    /**
     * @Route("/bloquer/{id}", name="profil_bloquer", requirements={"id": "\d+" });
     */
    public function bloquer($id, EntityManagerInterface $em){

        $userRepo = $this->getDoctrine()->getRepository(Utilisateur::class);
        $utilisateur =$userRepo->find($id);

        if($utilisateur->getActif()==true){
            $utilisateur->setActif(false);
            $em->persist($utilisateur);
            $em->flush();
        } else {
            $utilisateur->setActif(true);
            $em->persist($utilisateur);
            $em->flush();
        }

        $userRepo = $this->getDoctrine()->getRepository(Utilisateur::class);
        $utilisateurs =$userRepo->findAll();

        $photoRepo = $this->getDoctrine()->getRepository(Photo::class);
        $photo = $photoRepo->find(2);

        return $this->redirectToRoute('profils',[
            "utilisateurs"=>$utilisateurs, "photo"=>$photo
        ]);
    }

    /**
     * @Route("/supprimer/{id}", name="profil_supprimer", requirements={"id": "\d+" });
     */
    public function supprimer($id, EntityManagerInterface $em){

        $userRepo = $this->getDoctrine()->getRepository(Utilisateur::class);
        $utilisateur =$userRepo->find($id);

        if($utilisateur->getActif()==true){
            $this->addFlash('success', 'Attention vous souhaitez supprimer un utilisateur !! L\'utilisateur dois être désactivé avant !!');
        } else {
            $em->remove($utilisateur);
            $em->flush();
        }

        $userRepo = $this->getDoctrine()->getRepository(Utilisateur::class);
        $utilisateurs =$userRepo->findAll();

        $photoRepo = $this->getDoctrine()->getRepository(Photo::class);
        $photo = $photoRepo->find(2);

        return $this->redirectToRoute('profils',[
            "utilisateurs"=>$utilisateurs, "photo"=>$photo
        ]);
    }

    /**
     * @Route("/profil_afficher/{id}", name="profil_afficher", requirements={"id": "\d+" })
     */
    public function afficher($id){

        //id == id de la sortie
        $sortieRepo = $this->getDoctrine()->getRepository(Sortie::class);
        $sortie =$sortieRepo->find($id);

        $userRepo = $this->getDoctrine()->getRepository(Utilisateur::class);
        $utilisateurs =$userRepo->findAll();

        $utilisateur = new Utilisateur();

        foreach ($utilisateurs as $utilisateur1){
            if($utilisateur1->getUsername()==$sortie->getOrganisateur()->getUsername()){
                $utilisateur=$utilisateur1;
            }
        }
       $photo = $utilisateur->getNomPhoto();

        return $this->render('profil/profil_afficher.html.twig', ["photo"=>$photo, "utilisateur"=>$utilisateur]);
    }

}

templates/profil/inscription.html.twig
{% extends 'layout.html.twig' %}

{% block main %}
    <div id="formProfil">
        <h2 id="h2Inscription">Inscription</h2>
        <div>
             {{ form_start(formInscription) }}
            {{ form_widget(formInscription) }}
        <div id="btnProfil">
            <button type="submit" id="submit" name="submit">Enregistrer</button>
            <button type="reset" id="reset" name="reset">Annuler</button><br><br>
        </div>
    </div>
    {{ form_end(formInscription) }}
{% endblock %}

templates/profil/profil.html.twig
{% extends 'layout.html.twig' %}

{% block main %}
    <h2 id="h2Profil"> Modifier Profil</h2>
    <div id="container">
        <div id="photoProfils">
            <img src="{{ asset('photos/') ~photo }} " width="150" alt="">
        </div>
        <div class="formProfil form-inline">
            {{ form_start(formInscription) }}
            {% if app.user.administrateur==0 %}
                {{ form_widget(formInscription.administrateur, {'disabled' : true, 'attr' : { 'hidden' : true}} ) }}
                {{ form_widget(formInscription.actif, {'disabled' : true, 'attr' : { 'hidden' : true}}) }}
            {% endif  %}
            {{ form_widget(formInscription) }}

            <div id="btnProfil">
                <button type="submit" id="submit" name="submit">Enregistrer</button>
                <button type="reset" id="reset" name="reset">Annuler</button><br><br>
            </div>
                {{ form_end(formInscription) }}
        </div>
    </div>


{% endblock %}

templates/profil/profil_afficher.html.twig
{% extends 'layout.html.twig' %}

{% block main %}

    <h1>Afficher Profil {{ utilisateur.username }}</h1>

    <div>
            <label>Nom:</label>{{ utilisateur.nom }} <br>
            <label>Prenom :</label>{{ utilisateur.prenom}} <br>
            <label>Téléphone :</label>{{ utilisateur.telephone }} <br>
            <label>Email :</label>{{ utilisateur.email }} <br>
            <label>Campus :</label>{{ utilisateur.campus.nomCampus }} <br>
    </div>
<form method="post">
    <br> <a id="creerSortie" href="{{ path('accueil') }}">Retour</a>
</form>
{% endblock %}

templates/profil/profils.html.twig
{% extends 'layout.html.twig' %}

{% block main %}
    {% for utilisateur in utilisateurs %}
        <article id="articleProfils">
            {% if utilisateur.username != app.user.username %}
                <h3 id="titreProfil">Profil de {{ utilisateur.username }}</h3>
            {% else %}
                <h3 id="titreProfil">Votre Profile !!</h3>
            {% endif %}

            {% if utilisateur.nomPhoto is empty %}
                <div id="photoProfils">
                    <br><br>
                </div>            {% else %}
                <div id="photoProfils">
              <br><br>  <img src="{{ asset('photos/') ~utilisateur.nomPhoto }} " width="150" alt="">
                </div>
            {% endif %}
            <div id="profils">
                <label>Pseudo :           </label>{{ utilisateur.username }} <br>
                <label>Nom :              </label>{{ utilisateur.nom }} <br>
                <label>Prenom :           </label>{{ utilisateur.prenom}} <br>
                <label>Téléphone :        </label>{{ utilisateur.telephone }} <br>
                <label>Email :            </label>{{ utilisateur.email }} <br>
                <label>Id Utilisateur :   </label>{{ utilisateur.UserId }} <br>
                <label>Campus :           </label>{{ utilisateur.campus.nomCampus }} <br>
                <label>Administrateur :   </label>
                {% if utilisateur.administrateur==1 %}
                    Oui
                {% else %}
                    Non
                {% endif %}<br>
                <label>Actif :            </label>
                {% if utilisateur.actif==1 %}
                    Oui
                {% else %}
                    Non
                {% endif %}<br>
                <label>Password :         </label>{{ utilisateur.password}} <br>
                {% for message in app.flashes('success') %}
                    <div class="alert alert-success">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
            <div id="actionsProfils">
                <button class="btnAdministrateur"><a href="{{ path('profil_modifier', {'id':utilisateur.userId}) }}">Modifier</a></button>
                {% if utilisateur.actif==1 %}
                    <button class="btnAdministrateur"><a href="{{ path('profil_bloquer', {'id':utilisateur.userId}) }}">Bloquer</a></button>
                {% else %}
                    <button class="btnAdministrateur"><a href="{{ path('profil_bloquer', {'id':utilisateur.userId}) }}">Débloquer</a></button>
                {% endif %}
                <button class="btnAdministrateur"><a href="{{ path('profil_supprimer', {'id':utilisateur.userId}) }}">Supprimer</a></button>
            </div>
        </article><br><br>
    {% endfor %}
{% endblock %}