src/Entity/Sortie.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @ORM\Table(name="sortie")
 * @ORM\Entity(repositoryClass="App\Repository\SortieRepository")
 */
class Sortie extends AbstractController
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $SortieId;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $nomSortie;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $etat;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateHeure;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateLimiteInscription;

    /**
     * @ORM\Column(type="string", length=10000, nullable=true)
     */
    private $inscrie;

    /**
     * @ORM\Column(type="string", precision=3)
     */
    private $nbplaces;

    /**
     * @ORM\Column(type="integer", precision=3)
     */
    private $duree;

    /**
     * @ORM\Column(type="text")
     */
    private $description;


    /**
     * @var Sortie
     * @ORM\ManyToOne(targetEntity="App\Entity\Villes", inversedBy="sorties")
     * @ORM\JoinColumn(nullable=true, name="Villes", referencedColumnName="villes_id")
     */
    private $ville;

    /**
     * @var Sortie
     * @ORM\ManyToOne(targetEntity="App\Entity\Campus", inversedBy="sorties")
     * @ORM\JoinColumn(nullable=true, name="Campus", referencedColumnName="campus_id")
     */
    private $campus;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $rue;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $codePostal;

    /**
     * @var Utilisateur
     * @ORM\ManyToOne(targetEntity="App\Entity\Utilisateur", inversedBy="sorties")
     * @ORM\JoinColumn(nullable=true, name="organisateur", referencedColumnName="user_id")
     */
    private $organisateur;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $motifAnnulation;

    /**
     * @return mixed
     */
    public function getSortieId()
    {
        return $this->SortieId;
    }

    /**
     * @param mixed $SortieId
     */
    public function setSortieId($SortieId): void
    {
        $this->SortieId = $SortieId;
    }

    /**
     * @return mixed
     */
    public function getNomSortie()
    {
        return $this->nomSortie;
    }

    /**
     * @param mixed $nomSortie
     */
    public function setNomSortie($nomSortie): void
    {
        $this->nomSortie = $nomSortie;
    }

    /**
     * @return mixed
     */
    public function getDateHeure()
    {
        return $this->dateHeure;
    }

    /**
     * @param mixed $dateHeure
     */
    public function setDateHeure($dateHeure): void
    {
        $this->dateHeure = $dateHeure;
    }

    /**
     * @return mixed
     */
    public function getDateLimiteInscription()
    {
        return $this->dateLimiteInscription;
    }

    /**
     * @param mixed $dateLimiteInscription
     */
    public function setDateLimiteInscription($dateLimiteInscription): void
    {
        $this->dateLimiteInscription = $dateLimiteInscription;
    }

    /**
     * @return mixed
     */
    public function getNbplaces()
    {
        return $this->nbplaces;
    }

    /**
     * @param mixed $nbplaces
     */
    public function setNbplaces($nbplaces): void
    {
        $this->nbplaces = $nbplaces;
    }

    /**
     * @return mixed
     */
    public function getDuree()
    {
        return $this->duree;
    }

    /**
     * @param mixed $duree
     */
    public function setDuree($duree): void
    {
        $this->duree = $duree;
    }

    /**
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param mixed $description
     */
    public function setDescription($description): void
    {
        $this->description = $description;
    }

    /**
     * @return mixed
     */
    public function getVille()
    {
        return $this->ville;
    }

    /**
     * @param mixed $ville
     */
    public function setVille($ville): void
    {
        $this->ville = $ville;
    }

    /**
     * @return mixed
     */
    public function getRue()
    {
        return $this->rue;
    }

    /**
     * @param mixed $rue
     */
    public function setRue($rue): void
    {
        $this->rue = $rue;
    }

    /**
     * @return mixed
     */
    public function getCodePostal()
    {
        return $this->codePostal;
    }

    /**
     * @param mixed $codePostal
     */
    public function setCodePostal($codePostal): void
    {
        $this->codePostal = $codePostal;
    }

    /**
     * @return mixed
     */
    public function getEtat()
    {
        return $this->etat;
    }

    /**
     * @param mixed $etat
     */
    public function setEtat($etat): void
    {
        $this->etat = $etat;
    }

    /**
     * @return mixed
     */
    public function getOrganisateur()
    {
        return $this->organisateur;
    }

    /**
     * @param Sortie $organisateur
     */
    public function setOrganisateur(Utilisateur $organisateur): void
    {
        $this->organisateur = $organisateur;
    }

    /**
     * @return mixed
     */
    public function getInscrie()
    {
        return $this->inscrie;
    }

    /**
     * @param mixed $inscrie
     */
    public function setInscrie($inscrie): void
    {
        $this->inscrie = $inscrie;
    }

    /**
     * @return mixed
     */
    public function getCampus()
    {
        return $this->campus;
    }

    /**
     * @param mixed $campus
     */
    public function setCampus($campus): void
    {
        $this->campus = $campus;
    }

    /**
     * @return mixed
     */
    public function getMotifAnnulation()
    {
        return $this->motifAnnulation;
    }

    /**
     * @param mixed $motifAnnulation
     */
    public function setMotifAnnulation($motifAnnulation): void
    {
        $this->motifAnnulation = $motifAnnulation;
    }

}

templates/accueil.html.twig
{% extends 'layout.html.twig'%}


{%  block main %}

    <!-- Parti uniquement visible sur smartphone -->
<div class="d-block d-md-none">
    <h3><img src="{{ asset('photos/Local/') ~'24730e81feb5acfc65d93c6dd9ec8487.png' }} " width="35" alt=""><a class="aMenu" href="{{ path('accueil') }}">  Sortir.com</a></h3>
    <table class="tableauSortie">
        <h3>Mes Sorties :</h3>
        <thead>
        <tr>
            <th>Nom de la sortie</th>
            <th >Date de la sortie</th>
            <th >Lieux</th>
        </tr>
        </thead>
        <tbody>
        {% for sortie in sorties %}
        <tr>
            <td align="center"><a href="{{ path('sortie_afficher', {'id':sortie.sortieId }) }}">{{ sortie.nomSortie }} </a></td>
            <td align="center">{{ sortie.dateHeure|date("d/m/Y H") }}h   </td>
            <td align="center">{{ sortie.ville.nomVilles }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

</div>
    <!--Parti uniquement visible sur tablette et ordinateur -->

    <!-- ////////////////////////  Filtre  ///////////////////////////////////-->
    <button id="btnFiltre">Filtres</button>

<div id="divFiltre" >
    <br><h3>Filtrer les sorties</h3>
    <form method="post" action="{{ path('accueil') }}" id="formFiltre" name="filtre" class="filtre">

        <div id="form1">
            <div id="b1">
                <label for="search"> Nom de la sortie:</label>
                <input id="search" name="search" type="text">
            </div>

        <div id="b2">
            <label>Entre:</label>
            <input name="dateDebut" type="date">
            <label>et:</label>
            <input name="dateFin"  type="date">
        </div>

            <div id="b6">
               <label>Campus</label>
               <select id="selecCampus" name="selectCampus"  >
                   {% for camp in campus %}
                         {% if camp == app.user.campus %}
                               <option {{ optionUser }} value="{{ camp.nomCampus }}" >{{ camp.nomCampus }}</option>
                         {% endif %}
                         {% if camp != app.user.campus and camp.nomCampus != selectCampus%}
                            <option value="{{ camp.nomCampus }}" >{{ camp.nomCampus }}</option>
                         {% endif %}
                       {% if camp != app.user.campus and camp.nomCampus == selectCampus%}
                           <option value="{{ camp.nomCampus }}" {{ optionOther }} >{{ camp.nomCampus }}</option>
                       {% endif %}
                   {% endfor %}
               </select><br>
            </div>

            <div id="b4" class="filtre_3 col-md-3">
                <button name="rechercher">Rechercher</button>
            </div>
        </div>

        <div id="form2">
            <!-- /////////////    Les Checkbox  //////////////////////////// -->
                <input type="checkbox" class="ib6" id="organisateur" name="organisateur" {{ organisateurCheck }} ><label>Sorties dont je suis l'organisateur/trice</label><br>
                <input type="checkbox" class="ib6" id="inscrit" name="inscrit" {{ inscritCheck }} ><label>Sorties auxquelles je suis inscrit/e</label><br>
                <input type="checkbox" class="ib6" id="pasInscrit" name="pasInscrit"{{ pasInscritCheck}} ><label>Sorties auxquelles je ne suis pas inscrit/e</label><br>
                <input type="checkbox" class="ib6" id="passees" name="passees" {{ passeesCheck }} ><label>Sorties passées</label>
        </div>
    </form><br><br>

    <!-- ///////////////// Le tableau des Sorties /////-->
</div>
        <table class="tableauSortie col-md-12 col-lg-12 d-none d-md-block">
            <thead>
            <tr>
                <th>Nom de la sortie</th>
                <th >Date de la sortie</th>
                <th >Clôture</th>
                <th>Inscrits/Places</th>
                <th>Etat</th>
                <th>Inscrit</th>
                <th>Organisateur</th>
                <th>Actions</th>
                {% if app.user.administrateur==1 %}
                    <th>Actions Administrateur</th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for sortie in sorties|filter(sortie=> dateDebut<sortie.dateHeure|date("Y-m-d") and dateFin>sortie.dateHeure|date("Y-m-d")) %}
                {% if search == "search"   %}
                     {% for sortieRecherche in tableauRecherche %}
                        {% if (sortieRecherche == sortie.nomSortie ) %}
                            {% include 'accueilBody.html.twig' %}
                         {% endif %}
                     {% endfor %}
                {% else %}
                    {% include 'accueilBody.html.twig' %}
                {% endif %}
            {% endfor %}

            {% for sortie in sorties2|filter(sortie=> sortie.campus.nomCampus != selectCampus and dateDebut<sortie.dateHeure|date("Y-m-d") and dateFin>sortie.dateHeure|date("Y-m-d")) %}
                    {% include 'accueilBody.html.twig' %}
            {% endfor %}

            {% for sortie in sorties3|filter(sortie=> sortie.campus.nomCampus != selectCampus  and sortie.organisateur.username != app.user.username and dateDebut<sortie.dateHeure|date("Y-m-d") and dateFin>sortie.dateHeure|date("Y-m-d")) %}
                    {% include 'accueilBody.html.twig' %}
            {% endfor %}

            {% for sortie in sorties4|filter(sortie=> sortie.campus.nomCampus != selectCampus and  sortie.organisateur.username != app.user.username and dateDebut<sortie.dateHeure|date("Y-m-d") and dateFin>sortie.dateHeure|date("Y-m-d")) %}
                    {% include 'accueilBody.html.twig' %}
            {% endfor %}
            {% if sorties != "premiereBoucle" %}
            {% for sortie in sorties5|filter(sortie=> sortie.campus.nomCampus == selectCampus and dateDebut<sortie.dateHeure|date("Y-m-d") and dateFin>sortie.dateHeure|date("Y-m-d")) %}
                {% include 'accueilBody.html.twig' %}
            {% endfor %}
            {% endif %}

            </tbody>
        </table><br>

    <div class="col d-none d-md-block">
        <a id="creerSortie" href="{{ path('sortie_creation') }}">Créer une sortie</a>
    </div><br>
{% endblock %}
{% block title %}Accueil{% endblock %}

templates/accueilBody.html.twig
                <tr>
                    <td align="center">{{ sortie.nomSortie }}</td>
                    <td align="center">{{ sortie.dateHeure|date("d/m/Y H") }}h   </td>
                    <td align="center">{{ sortie.dateLimiteInscription|date("d/m/Y") }}</td>
                    {% set sortieInscrit = sortie.inscrie|split('-') %}
                    <td align="center">{{ (sortieInscrit|length)-1 }}/{{ sortie.nbplaces }}</td>
                    <td align="center">{{ sortie.etat }}</td>
                    {%if(app.user.username in sortie.inscrie) %}
                        <td align="center">X</td>
                    {% else %}
                        <td></td>
                    {% endif %}


                    <td align="center"><a href="{{ path('profil_afficher', {'id':sortie.sortieId }) }}">{{ sortie.organisateur.username }} </a></td>
                    <td align="center">

                        {%  if (sortie.etat == "Ouverte" or sortie.etat =="Annulée") %}
                        <a href="{{ path('sortie_afficher', {'id':sortie.sortieId }) }}">Afficher</a>
                        {% endif %}

                        {%if(app.user.username in sortie.inscrie and sortie.dateLimiteInscription|date("Y-m-d")> "now"|date("Y-m-d") ) %}
                            <a href="{{ path('sortie_desinscription', {'id':sortie.sortieId }) }}" >Se désinscrire</a>
                        {% elseif((sortieInscrit|length) < sortie.nbplaces) and (app.user.username!=sortie.organisateur.username) and sortie.etat =="Ouverte" %}
                            <a href="{{ path('sortie_inscription', {'id':sortie.sortieId }) }}">S'inscrire</a>
                        {% endif %}
                        {% if app.user.username==sortie.organisateur.username %}
                            {% if (sortie.dateLimiteInscription|date("Y-m-d")> "now"|date("Y-m-d") ) %}
                                <a href="{{ path('sortie_modifier', {'id':sortie.sortieId }) }}" >Modifier</a>
                            {%  endif %}
                            {% if (sortie.etat=="En création") %}
                                <a href="{{ path('sortie_publier', {'id':sortie.sortieId }) }}" >Publier</a>
                            {% endif %}
                        {% endif %}
                    </td>
                    {% if app.user.administrateur ==1 %}
                    <td align="conter">
                        {% if (sortie.dateLimiteInscription|date("Y-m-d")> "now"|date("Y-m-d") ) %}
                             <a href="{{ path('sortie_modifier', {'id':sortie.sortieId }) }}" >Modifier</a>
                        {%  endif %}
                        {% if (sortie.inscrie is empty and sortie.etat != "Annulée" and sortie.etat != "Fermée") %}
                           <a href="{{ path('sortie_annuler', {'id':sortie.sortieId }) }}" >Annuler</a>
                        {% endif %}
                     {% endif %}
                    </td>
                </tr>

templates/layout.html.twig
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Sortir.Com{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


    <link rel="stylesheet" href="/sortir.com/public/css/app.css">




</head>
<body>
    <header>

        <div class="titre">
            <h1 id="h1Layout">Sortir.com</h1>
        </div>

        <div class="nav">
            {% include 'nav/nav.html.twig' %}
        </div>

    </header>
    <main>
        {% block main %}

        {% endblock %}
    </main>
    <!--<footer>
        &copy; 20{{ "now"|date("y") }}

    </footer>-->
    <script>
        var button = document.querySelector('#btnFiltre');
        var divFiltre = document.querySelector('#divFiltre');

        button.addEventListener('click', filtre);

        function filtre() {

            if (divFiltre.style.display=='none'){
                divFiltre.style.display='block';
            }
            else{

                    divFiltre.style.display='none';


            }
        }
    </script>
</body>
</html>